# Generated by Django 5.1.1 on 2024-09-16 15:38

import django.db.models.deletion
import subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва сервісу.', max_length=255)),
                ('description', models.TextField(help_text='Опис сервісу.')),
                ('image', models.FileField(help_text='Зображення сервісу.', upload_to=subscriptions.models.upload_to)),
                ('bg_color', models.CharField(blank=True, help_text='Фоновий колір.', max_length=50)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services_table',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], help_text='Назва тарифного плану.', max_length=50)),
                ('benefits', models.JSONField(blank=True, default=list, help_text='Переваги тарифного плану.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Ціна підписки.', max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Тривалість підписки в місяцях (наприклад, 1, 6, 12).')),
                ('is_active', models.BooleanField(default=True, help_text='Визначає, чи активний план.')),
                ('service', models.ForeignKey(help_text='Сервіс, до якого відноситься план.', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='subscriptions.service')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'subscriptions_plan_table',
            },
        ),
    ]
