# Generated by Django 5.1.1 on 2024-09-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(upload_to='product/'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
