# Generated by Django 5.1.1 on 2024-09-08 15:04

import subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_service_image_delete_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(upload_to=subscriptions.models.upload_to),
        ),
    ]
