# Generated by Django 5.1.1 on 2024-09-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscriptionplan_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='bg_color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
