# Generated by Django 5.1.1 on 2024-11-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
