# Generated by Django 5.1.1 on 2024-09-16 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Дата початку підписки.')),
                ('end_date', models.DateField(help_text='Дата завершення підписки.')),
                ('is_active', models.BooleanField(default=True, help_text='Визначає, чи активна підписка.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', help_text='Статус підписки.', max_length=20)),
                ('plan', models.ForeignKey(help_text='Тарифний план підписки.', on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan')),
                ('service', models.ForeignKey(help_text='Сервіс, до якого відноситься підписка.', on_delete=django.db.models.deletion.CASCADE, to='subscriptions.service')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions_table',
            },
        ),
    ]
